#!/bin/bash
APPNAME="${1}"
MODE="${2}"
ARG="${3}"
APP="${APPNAME}.app"
APPHOME="/Applications/"
ACTION="Opened"
APPPATH="${APPHOME}/${APP}"
NOTIFICATION_SCRIPT="${HOME}/bin/notify"

function ensure_running {
    RESULT=`ps x | grep ${APP} | grep -v grep`
    if [[ $RESULT == "" ]]
    then
        open_app
        sleep 1
        ${NOTIFICATION_SCRIPT} ${APPNAME} "false" "${ACTION}" "${APPNAME}" "" "${APPNAME}"
    fi
}

function open_app {
    if [[ "${APPNAME}" =~ "Firefox" ]]; then
        ${APPPATH}/Contents/MacOS/firefox -P ${APPNAME##Firefox} &
    elif [ -d ${APPPATH} ]; then
        open "${APPPATH}"
    fi
}

function open_link {
    if [[ $1 == 'bg' ]]; then
        background="-g"
    fi
    notification_message="Invalid link provided."
    link_candidate=$2
    if [[ $2 == '' ]]; then
        link_candidate="$(echo `pbpaste`)"
        notification_message="No link on pasteboard"
    elif [[ $2 == 'NOTFOUND' ]]; then
        notification_message="No link found."
    fi
    echo "${link_candidate}"

    if [ -d ${APPPATH} ]; then
        if [[ "${link_candidate}" =~ ^http ]]; then
            open -a "${APPPATH}" ${background} "${link_candidate}"
            ${NOTIFICATION_SCRIPT} ${APPNAME} "false" "${link_candidate}" "${APPNAME}" "" "${APPNAME}"
        else
            ${NOTIFICATION_SCRIPT} ${APPNAME} "false" "${notification_message}" "${APPNAME}" "" "${APPNAME}"
        fi
    fi
}

function activate_app {
ensure_running
osascript <<END_SCRIPT
tell application "${APP}"
    activate
end tell
END_SCRIPT
}

function last_tab {
osascript <<END_SCRIPT
tell application "${APP}"
    activate
    tell application "System Events"
        key code 53 -- escape key
        keystroke "g"
        keystroke "$"
    end tell
end tell
END_SCRIPT
}

function bounce_app {
    RESULT=`killall -s ${APPNAME} 2>/dev/null`
    if [[ $RESULT != "" ]]; then
        killall ${APPNAME} 2>/dev/null
        sleep 1
        ACTION="Restarted"
    fi
    ensure_running
}

if [[ $MODE == "bounce" ]]; then
    bounce_app
elif [[ $MODE == "activate" ]]; then
    activate_app
elif [[ $MODE == "open" ]]; then
    open_app
elif [[ $MODE == "ensure" ]]; then
    ensure_running
elif [[ $MODE == "link" ]]; then
    open_link 'fg' "${ARG}"
    last_tab
elif [[ $MODE == "blink" ]]; then
    open_link 'bg' "${ARG}"
elif [[ $MODE == "" ]]; then
    ensure_running
fi
