#!/bin/sh
CHATS="/home/seth/.weechat/logs"
PCHATS="/home/seth/.weechat_personal/logs"
CHAT1="${PCHATS}/irc.bitlbee.tadhg.weechatlog"
#CHAT2="${CHATS}/irc.slack-ua.#production-changes.weechatlog"
CHAT2="${CHATS}/python.ua.#reach-sentry.weechatlog"
CHAT3="${CHATS}/python.ua.#channel-wallet.weechatlog"
CHAT4="${CHATS}/python.ua.#wallet-eng.weechatlog"
CHAT5="${CHATS}/python.ua.&wallet-team.weechatlog"

location=$(which multitail 1&> /dev/null)
if [ ! -e ${location:-NOTFOUND} ]; then
    echo "multitail not found"
    return 1
fi
if [ $# -eq 1 ]; then
    echo "Specify a chat profile: personal, ua"
    exit 1
elif [ $# -eq 2 ]; then
    CHAT_PROFILE=$1
    CHAT_ID=$2
    case $CHAT_PROFILE in
        "personal")
            CHAT="${PCHATS}/${CHAT_ID}.weechatlog"
            ;;
        "ua")
            CHAT="${CHATS}/python.ua.${CHAT_ID}.weechatlog"
            ;;
    esac
    /bin/less +F ${CHAT}
else
    multitail -Z red,black,inverse -T -x "%m %u@%h %f (%t) [%l]" -b 8 -m 50 -n 50 -f "${CHAT1}" -m 50 -n 50 -f "${CHAT2}" -m 50 -n 50 -f "${CHAT3}" -m 50 -n 50 -f "${CHAT4}" -m 50 -n 50 -f "${CHAT5}"
fi
