#!/bin/bash
# TODO: use something better than year (date with format) for awk part
# TODO: better handle missing timestamp
# TODO: configurable top n items?
# TODO: supporting vim function to retreive preformatted values?
# TODO: add line about adding to crontab & what the entry should look like
# */15 * * * * /Users/seth/bin/currentstatus 1&> /dev/null
NOTIFICATION_SCRIPT="${HOME}/bin/notify"
STATE="taskstack"
if [ ${HOSTNAME} == "seth.local" ]; then
    FILE="${HOME}/sandbox/work/work.tst.txt"
else
    FILE="${HOME}/sandbox/personal/todo/personal.tst.txt"
fi
RESULT=`head -6 ${FILE} | grep -v '^$' | grep -v 'DOING' | grep -v 'WTF' | grep -v '^@' | grep -v '{{{|}}}' | awk -F'201.-' '{print $1}'`
echo "${RESULT}"
${NOTIFICATION_SCRIPT} $(basename $0) "false" "${RESULT}" "${STATE}"
