#!/usr/local/bin/zsh
CWD=$HOME/Library/Application\ Support/Firefox/Profiles
TIMESTAMP=`date +%Y-%m-%d.%T`
cd $CWD
git add -f **/sessionstore.js
git add -f **/sessionstore-backups/*.js
git commit -m"$TIMESTAMP"
