#!/bin/bash
GROUP="wallet-1-igm"

case $(basename $0) in
    gcp-eucs)
        REGION="europe-west1"
        PROJECT="ua-ops-transitional-eucs"
        ;;
    gcp-stag)
        REGION="us-east1"
        PROJECT="ua-ops-transitional-stag"
        ;;
    gcp-prod)
        REGION="us-east1"
        PROJECT="ua-ops-transitional-prod"
        ;;
    *)
        echo "Please use an appropriately named symlink to this command."
        exit 1
        ;;
esac

selection=$1

instances_command="gcloud compute instance-groups list-instances --project $PROJECT --region $REGION $GROUP --format=csv[no-heading](instance.basename(),instance.scope(zones).segment(0))"
instances_result=($($instances_command))

declare -a available_instances
i=0
while IFS="," read -r instance zone; do
    ((i++))
    id=$(echo $instance | awk -F'-' '{print $NF}')
    available_instances[$i]="$id $instance $zone"
done <<< "$instances_result"


if [[ -z $selection && ${#instances[@]} -gt 1 ]]; then
    echo "Multiple instances available:"
    echo ""
    for i in ${!available_instances[@]}; do
        current=(${available_instances[$i]})
        echo "$i: ${current[1]} (${current[2]})"
    done
    echo ""
    echo "Choose a number and press [ENTER]:"
    read selection
    if [[ -z $selection ]]; then
        exit 0
    fi
else
    selection=1
fi

selected_instance=(${available_instances[$selection]})
name=${selected_instance[1]}
zone=${selected_instance[2]}

COMMAND="gcloud compute --project $PROJECT ssh --zone $zone $name"
echo $COMMAND
$COMMAND
