#!/usr/bin/env ruby

# TODO: use colors in output

def gitworld(command)
    home = ENV["HOME"]
    paths = [                                      \
        "bin",                     \
        "",                         \
        ".vim",                    \
        ".vim/bundle/vim-traitor", \
        ".vim/bundle/vimple",      \
        ".pentadactyl",            \
        "sandbox/personal",        \
        ".oh-my-zsh"               \
    ]
    paths.each do |path|
        fullpath = "#{home}/#{path}"
        if File.directory? fullpath
            Dir.chdir("#{fullpath}")
            output = %x[ git #{command}]
            printf "============================[ %30s ]=======\n%s", path, output
        end
    end
end

if ARGV[0].nil?
    command = "state"
else
    command = ARGV
end

puts "Running `git #{command}` on all repositories..."
gitworld command

# vim: set ft=ruby
