#!/bin/bash
git status -s | awk "
/^\?\? /     { untracked++ };
/^[AM]  /    { added++     };
/^[A ][MT] / { modified++  };
/^R  /       { renamed++   };
/^[A ]D /    { deleted++   };
/^UU /       { unmerged++  };
/^C  /       { copied++    };

END {

    status[\"deleted\"]   = deleted+0     \"✖\";
    status[\"modified\"]  = modified+0    \"▹\";
    status[\"renamed\"]   = renamed+0     \"➜\";
    status[\"untracked\"] = untracked+0   \"✭\";
    status[\"added\"]     = added+0       \"✚\";
    status[\"unmerged\"]  = unmerged+0    \"⇋\";
    status[\"copied\"]    = copied+0      \"ⓒ\";

    for (i in status) {
        if (status[i]+0 != 0) {
            printf(status[i] \" \");
        }
    }
}
"
