#!/usr/bin/env ruby
require 'open3'
include Open3

# TODO: use colors in output
# TODO: use config file for repo locations

def gitworld(command)
    home = ENV["HOME"]
    trans = "/Volumes/trans/repos"
    paths = [                      \
        "",                        \
        "bin",                     \
        ".vim",                    \
        ".pentadactyl",            \
        ".oh-my-zsh"               \
        ".tmux"                    \
        "sandbox/work",            \
        "sandbox/personal",        \
        "#{trans}/personal",       \
        "#{trans}/binfiles",       \
        "#{trans}/vimfiles",       \
        "#{trans}/dotfiles",       \
        "#{trans}/pentafiles",     \
    ]
    paths.each do |path|
        fullpath = path.start_with?("/") ? "#{path}" : "#{home}/#{path}"
        if File.directory? fullpath
            Dir.chdir("#{fullpath}")
            popen3("git #{command}") do |stdin, stdout, stderr, wait_thr|
                output = stdout.read
                error = stderr.read
                printf "============================[ %30s ]=======\n%s", path, output
                puts "" if output.length > 0
                print stderr.read
                puts "" if error.length > 0
            end
        end
    end
end

if ARGV[0].nil?
    command = "state"
else
  command = ARGV.join(" ")
end

puts "Running `git #{command}` on all repositories..."
gitworld command

# vim: set ft=ruby
