#!/usr/bin/python
#
# grun
#
# Run a commandline that posts a growl notification when it completes.
# Each command gets its own individual sticky notification that is updated on completion.
#
# TODO: better support && compound commands, e.g. grun.py (echo "Initial output." && sleep 5 && echo "Final output."); works now with quotes surrounding ().
from sys import argv
import os, subprocess, string, shlex

original_command = " ".join(argv[1:])

def postnotification( identifier, title, message ):
    os.system( "notify grun true \"" + message + "\" '" + title + "' " + str(identifier) )

#os.system( "echo Executing with Growl completion notification: " + original_command )
p = subprocess.Popen( original_command, shell=True )
postnotification( p.pid, "running shell command", original_command )
status = os.waitpid( p.pid, 0 )[1]
postnotification( p.pid, "shell command completed" + " (" + str(status) + ")", original_command )
