#!/bin/sh
# Java heap size, in megabytes
JAVA_HEAP_SIZE=32
DEFAULT_JAVA_HOME="/System/Library/Frameworks/JavaVM.framework/Versions/1.4.2/Home"
if [ "$JAVA_HOME" = "" ]; then
JAVA_HOME="$DEFAULT_JAVA_HOME"
fi
exec "$JAVA_HOME/bin/java" -mx${JAVA_HEAP_SIZE}m ${JEDIT} -jar "/Applications/Applications3rd/jedit.jar" $@
