#!/bin/sh

# Symlink this as vimpager and vimcat to provide additional protections for
# using them including directories and non-text files.

colorls() {
    case $(uname -s) in
        "Darwin")
            /bin/ls -alG $file
            ;;
        *)
            /bin/ls -al --color=always $file
            ;;
    esac
}

resolved_file() {
    #local file="${1}"
    case $(uname -s) in
        "Linux")
            echo $(resolve_link_linux "${file}")
            ;;
        "Darwin")
            echo $(resolve_link_macos "${file}")
            ;;
    esac
}

resolve_link_macos() {
    link=$(readlink ${file})
    if [ -n "${link}" ]; then
        echo $(which ${link})
    else
        echo "${file}"
    fi
}

resolve_link_linux() {
    if [ -n "${file}" ]; then
        echo $(readlink -f ${file})
    else
        echo "${file}"
    fi
}

istext() {
    local resolved_file=$(resolved_file $1)
    local check="$(file "${resolved_file}" | awk -F':' '{print $2}' | grep -v text)"
    if [ -z "${check}" ]; then
        echo true
    else
        echo false
    fi
}

pageit() {
    "${HOME}/.vim/bundle/vimpager/$(basename ${0})" $@
}

pagerwrap() {
    if [ $# -gt 1 ]; then
        pageit "$@"
    elif [ -d "${file}" ]; then
        colorls "${file}"
    elif [ "$(istext ${file})" = "false" ]; then
        file "${file}"
    else
        pageit "$@"
    fi
}

file=$1
pagerwrap "$@"

# vim:et:ts=4 sw=4
