#!/bin/sh
REMOTE_SERVER="samsara" # Defined in ~/.ssh/config
TARGET_SCRIPT="~/Library/Scripts/applescripts/playpause.applescript"
ssh ${REMOTE_SERVER} osascript ${TARGET_SCRIPT}
RESULT=`ssh ${REMOTE_SERVER} osascript << END
tell app "iTunes"
	activate
	get player state
end tell
END`
/usr/local/bin/growlnotify --identifier "playpause" -a 'iTunes.app' -t 'iTunes' -m "${RESULT}"
