#!/bin/sh
#
# ps via growl
#
RESULT=`ps -o command | grep -v bash | grep -v COMMAND | grep -v mandoc | grep -v grep | grep -v screen | grep -v sort | grep -v awk | grep -v "^/bin/sh" | sort | awk -F'\t' '{print "- " $1}'`
/usr/local/bin/growlnotify --identifier "processes" -a 'Terminal.app' -t "processes" -m "${RESULT}"
