#!/bin/sh
# Get ssh-agent variables from your current
# session when you login creates an executable
# refresh file with them.
SSHVARS="SSH_CLIENT SSH_TTY SSH_AUTH_SOCK SSH_CONNECTION DISPLAY"

for x in ${SSHVARS} ; do
    (eval echo $x=\$$x) | sed  's/=/="/
                                s/$/"/
                                s/^/export /'
done 1>$HOME/bin/ssh-agent-refresh
chmod 600 $HOME/bin/ssh-agent-refresh
