#!/bin/sh
#
# synergy active remotely
#
NOTIFICATION_SCRIPT="${HOME}/bin/notify"
if [[ "${HOSTNAME}" == "samsara.local" ]]; then
    RESULT='laboratory.local'
else
    RESULT='samsara.local'
fi
${NOTIFICATION_SCRIPT} $(basename $0) "true" "${RESULT}"
