#!/bin/sh
if [ -f "$HOME/bin/ssh-agent-refresh" ]; then
    .  ${HOME}/bin/ssh-agent-refresh
fi
case "$1" in
    "out") tmux save-buffer - | ssh pasteboard-host pbcopy 2>/dev/null
        ;;
     "in") tmux set-buffer "$(ssh pasteboard-host pbpaste 2>/dev/null)"
        ;;
esac
