#!/bin/sh
#
# A script to select a Synergy configuration. Will attempt to autodetect network if no argument is given.
#
CONFIG_NAME=$1
#DEBUG_COMMAND=echo
DEBUG_COMMAND=
PRESET_NETWORK_NAMES="Available Presets: work, home"
DIRECTORY="/usr/local/bin"
LOGFILE="${HOME}/Desktop/synergy.log"
DEBUG_MODE="NOTE"
NOTIFICATION_SCRIPT="${HOME}/bin/notify"

function run {
    preconditions
    select_network ${CONFIG_NAME}
    exit 0
}

function autodetect {
    for TARGET in seth-pc.local seth.local laboratory.local
    do
        HOST=`scutil -r ${TARGET} | grep -q Directly && echo ${TARGET}`
        if [ -n "${HOST}" ]
        then
            break
        fi
    done
    echo ${HOST}
}

function select_network {
    case ${CONFIG_NAME} in
        "-ls")      echo ${PRESET_NETWORK_NAMES}
                    exit 0;
                    ;;
        "work")     DESTINATION="seth.local"
                    ;;
        "home")     DESTINATION="seth-pc.local"
                    ;;
        "lab")     DESTINATION="laboratory.local"
                    ;;
        *)          #echo Autodetected: `autodetect`
                    DESTINATION=`autodetect`
                    ;;
    esac


    case ${DESTINATION} in
        "seth.local")
            case ${HOSTNAME} in
                "samsara.local")    run_synergy client ${DESTINATION}
                                    ;;
                "seth.local")       run_synergy host with "${HOME}/bin/synergy.conf"
                                    ;;
            esac
            ;;
        "laboratory.local")
            case ${HOSTNAME} in
                "samsara.local")    run_synergy client ${DESTINATION}
                                    ;;
                "laboratory.local") run_synergy host with "${HOME}/bin/synergy-lab.conf"
                                    ;;
            esac
            ;;
        "seth-pc.local")            run_synergy client "seth-pc.local"
                                    #run_synergy host with "${figure this out}"
                                    ;;
    esac
}

function run_synergy {
    TYPE=$1
    DESTINATION=$2
    CONFIG=$3

    case ${TYPE} in
        "host")     COMMAND="${DIRECTORY}/synergys -f --name ${HOSTNAME} --debug ${DEBUG_MODE} --config ${CONFIG}"
                    LOGENTRY=$(echo ${HOSTNAME} "->" ${CONFIG})
                    ;;
        "client")   COMMAND="${DIRECTORY}/synergyc -f --name ${HOSTNAME} --debug ${DEBUG_MODE} ${DESTINATION}"
                    LOGENTRY=$(echo ${HOSTNAME} "->" ${DESTINATION})
                    ;;
    esac

    LOGLINE=$(echo `date +%Y-%m-%d\ %T\ %Z` '[ '${LOGENTRY}' ]')
    echo ${LOGLINE} ${COMMAND} >> ${LOGFILE}
    ${DEBUG_COMMAND} ${COMMAND} &> ${LOGFILE} &
    ${NOTIFICATION_SCRIPT} $(basename $0) "false" "${LOGENTRY}"
}

function preconditions {
    case "`uname`" in
        "Darwin")   ${DEBUG_COMMAND} killall -m synergy.
                    sleep 1
                    ;;
        "OpenBSD")  ;;
                *)  echo "This command only works in Mac OS X with SynergyKM installed."
                    exit 1
                    ;;
    esac
}
run
