#!/bin/sh
# A script to select a Synergy configuration. Will attempt to autodetect network if no argument is given.
CONFIG_NAME=$1
#DEBUG_COMMAND=echo
DEBUG_COMMAND=
PRESET_NETWORK_NAMES="Available Presets: work, home"
DIRECTORY="/Users/milliken/Library/PreferencePanes/SynergyKM.prefPane/Contents/Resources/Synergyd.app/Contents/Resources"
LOGFILE="~/Desktop/synergy.log"
DESTINATION=""
HOSTNAME="samsara"
DEBUG_MODE="NOTE"

function run {
	preconditions
	select_network ${CONFIG_NAME}
	exit 0
}

function autodetect {
	for TARGET in seth-g4.local. laboratory.local.
	do
		HOST=`scutil -r ${TARGET} | grep -q Directly && echo ${TARGET}`
		if [ -n "${HOST}" ]
		then
			break
		fi      
	done
	echo ${HOST}
}

function select_network {
	case ${CONFIG_NAME} in
		"-ls")		echo ${PRESET_NETWORK_NAMES}
					exit 0;
					;;
		"work")		DESTINATION="seth-g4.local."
					;;
		"home")		DESTINATION="laboratory.local."
					;;
		*)			#echo Autodetected: `autodetect`
					DESTINATION=`autodetect`
					;;
	esac

	case ${DESTINATION} in
		"seth-g4.local.")		COMMAND="${DIRECTORY}/synergyc -f --name ${HOSTNAME} --debug ${DEBUG_MODE} ${DESTINATION}"
								;;
		"laboratory.local.")	COMMAND="${DIRECTORY}/synergys -f --config ${HOME}/bin/synergy.conf --name samsara --debug ${DEBUG_MODE}"
								;;
	esac

	${DEBUG_COMMAND} ${COMMAND} &> ${LOGFILE} &
	echo ${DESTINATION}
}

function preconditions {
	case "`uname`" in
		"Darwin")	${DEBUG_COMMAND} killall -m synergy.
					;;
		"OpenBSD")	;; 	
				*)	echo "This command only works in Mac OS X with SynergyKM installed."
					exit 1
					;;
	esac
}
run
