#!/usr/bin/env ruby
#
# This is a script for modifying copies of iTerm2 to uniquely identify them.
#
DELETE = ["-d", "--delete"].include?(ARGV[0])

APP="iTerm"
ICONAPP="Firefox"
APP_ICON="AppIcon"
ORIG_CREATOR_CODE="ITRM"
CASKROOM="/opt/homebrew-cask/Caskroom"
CASK="iterm2"

app_specs = [
['ITR1' , 'Personal' , 'MatrixGreen.icns'       ],
#['ITR2' , 'VM'       , 'MatrixBlue.icns'  ],
#['ITR3' , 'Comm'     , 'MatrixGreen.icns' ],
#['ITR4' , 'Lists'    , 'MatrixGreen.icns' ],
]

class AppClone

  attr_accessor :creator_code, :name, :icon

  def initialize(spec)
    @creator_code, @name, @icon = spec
    @bundle_id = if /iTerm/ =~ @name
                   "com.googlecode.iterm2"
                 else
                   "com.googlecode.iterm2.#{@name}"
                 end
  end

  def install_root
    "/Applications"
  end

  def app_path
    "#{install_root}/#{@name}.app"
  end

  def contents_path
    "#{app_path}/Contents"
  end

  def original_root
    original_path = "/Applications/#{APP}.app"
    if File.exists? original_path
      return File.dirname(original_path)
    end
    original_path = Dir.glob("#{CASKROOM}/#{CASK}/**/#{APP}.app")
    if original_path.length > 0
      return File.dirname(original_path[-1])
    end
  end

  def copy_original
    unless File.exist? app_path
      printf "%s was not found. Copying...\n", app_path
      `cp -Rp "#{original_root}/#{APP}.app" "#{app_path}"`
      # Must initially launch copied app before modifying it.
      `open "#{app_path}"`
    end
  end

  def delete
    if File.exist? app_path
      printf "Deleting %s...\n", app_path
      `rm -rf "#{app_path}"`
    end
  end

  def clone
    delete if DELETE
    copy_original
    if File.exist? contents_path
      printf "Updating  %s (%s)...\n", "#{contents_path}", "#{@bundle_id}"
      `/usr/libexec/PlistBuddy #{contents_path}/Info.plist -c 'Set :CFBundleIdentifier '#{@bundle_id}`
      `/usr/libexec/PlistBuddy #{contents_path}/Info.plist -c 'Set :CFBundleName '#{@name}`
      `/usr/libexec/PlistBuddy #{contents_path}/Info.plist -c 'Set :CFBundleSignature '#{@creator_code}`
      copy_command="/bin/cp ~/Pictures/icons/#{ICONAPP}Icons/#{@icon} #{contents_path}/Resources/#{APP_ICON}.icns"
      `#{copy_command}` unless @icon.nil?
      # Wait a bit after launch to prevent treating the quit  as a crash
      `sleep 3`
      # Quit launched app after modifying it to pick up changes.
      `osascript -e 'quit app "#{@name}"'`
      # Trick to get Dock to pick up icon change
      `touch #{app_path}`
      printf "Created instance: %s at %s\n", @bundle_id, app_path
    end
  end

  def open
      `open "#{app_path}"`
  end

end

apps = []
for spec in app_specs do
  apps << AppClone.new(spec)
end
for app in apps
  app.clone
end
# To get Dock to pick up icon change
`killall Dock`
for app in apps
  app.open
end
