#!/bin/sh
#
# bus arrival notification
#
NOTIFICATION_SCRIPT="${HOME}/bin/notify"
TRANSIT_PAGE="http://trimet.org/arrivals/popup_tracker?locids=7747"
open -a 'Google Chrome.app' ${TRANSIT_PAGE}
RESULT="watch for bus arrival times"
${NOTIFICATION_SCRIPT} $(basename $0) "false" "${RESULT}" "Transit Alert"
