#!/bin/sh
#
# bus arrival notification
#
TRANSIT_PAGE="http://trimet.org/arrivals/popup_tracker?locids=7747"
open -a 'Google Chrome.app' ${TRANSIT_PAGE}
RESULT="watch for bus arrival times"
/usr/local/bin/growlnotify --identifier "transit_alert" -a 'Network Utility.app' -t "Transit Alert" -m "${RESULT}"
