#!/bin/sh
#
# bus arrival notification
#
NOTIFICATION_SCRIPT="${HOME}/bin/notify"
BART_STATION="MONT"
#TRANSIT_PAGE="http://nextbart.info/etd.html?station=CIVC&destination=DBRK"
#TRANSIT_PAGE="http://m.bart.gov/schedules/eta?stn=CIVC"
TRANSIT_PAGE="http://m.bart.gov/schedules/eta?stn=${BART_STATION}"
open -a 'Google Chrome.app' ${TRANSIT_PAGE}
RESULT="watch for bus arrival times"
${NOTIFICATION_SCRIPT} $(basename $0) "false" "${RESULT}" "Transit Alert"
